version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: mecanica-db
    restart: always
    environment:
      POSTGRES_DB: mecanica
      POSTGRES_USER: mecanica
      POSTGRES_PASSWORD: mecanica
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: mecanica-api
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  postgres_data: