services:

  postgres:
    image: postgres:16
    container_name: mecanica-db
    restart: always
    environment:
      POSTGRES_DB: mecanica
      POSTGRES_USER: mecanica
      POSTGRES_PASSWORD: mecanica
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mecanica -d mecanica"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: mecanica-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_JWT_SECRET: ${APP_JWT_SECRET:-techchallenge-secret-key-jwt-super-segura-2026}
      APP_AUTH_USERNAME: ${APP_AUTH_USERNAME:-admin}
      APP_AUTH_PASSWORD: ${APP_AUTH_PASSWORD:-123}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
