spring.application.name=mecanica

# ===============================
# DATASOURCE - POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/mecanica
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# DATABASE MIGRATIONS
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.sql.init.mode=never

# ===============================
# SERVER
# ===============================
server.port=8080

app.jwt.secret=${APP_JWT_SECRET:techchallenge-secret-key-jwt-super-segura-2026}
app.auth.username=${APP_AUTH_USERNAME:admin}
app.auth.password=${APP_AUTH_PASSWORD:123}
