spring.application.name=mecanica

# ===============================
# DATASOURCE - POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/mecanica
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# DATABASE MIGRATIONS
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.sql.init.mode=never

# ===============================
# SERVER
# ===============================
server.port=8080

app.jwt.public-key=${JWT_PUBLIC_KEY:}
app.jwt.issuer=${JWT_ISSUER:mecanica-auth}
