# Datasource (Docker)
spring.datasource.url=jdbc:postgresql://postgres:5432/mecanica
spring.datasource.username=mecanica
spring.datasource.password=mecanica
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Database migrations
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.sql.init.mode=never

# Logs
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql=INFO

server.port=8080

app.jwt.public-key=${JWT_PUBLIC_KEY:}
app.jwt.issuer=${JWT_ISSUER:mecanica-auth}
