apiVersion: v1
kind: ConfigMap
metadata:
  name: mecanica-api-config
  namespace: mecanica
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://mecanica-db:5432/mecanica
  SPRING_JPA_HIBERNATE_DDL_AUTO: update