apiVersion: v1
kind: Secret
metadata:
  name: mecanica-api-secret
  namespace: mecanica
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: admin
  APP_JWT_SECRET: "tech-challenge-fase-2-jwt-secret-demo"
  APP_AUTH_USERNAME: admin
  APP_AUTH_PASSWORD: "123"