apiVersion: v1
kind: ConfigMap
metadata:
  name: mecanica-api-config
  namespace: mecanica
data:
  APP_ENVIRONMENT: cloud
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_FLYWAY_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
