apiVersion: v1
kind: Service
metadata:
  name: mecanica-db
  namespace: mecanica
spec:
  selector:
    app: mecanica-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP